#pragma once

//From glfw3.h
#define VANTUS_MOUSE_BUTTON_1         0
#define VANTUS_MOUSE_BUTTON_2         1
#define VANTUS_MOUSE_BUTTON_3         2
#define VANTUS_MOUSE_BUTTON_4         3
#define VANTUS_MOUSE_BUTTON_5         4
#define VANTUS_MOUSE_BUTTON_6         5
#define VANTUS_MOUSE_BUTTON_7         6
#define VANTUS_MOUSE_BUTTON_8         7
#define VANTUS_MOUSE_BUTTON_LAST      VANTUS_MOUSE_BUTTON_8
#define VANTUS_MOUSE_BUTTON_LEFT      VANTUS_MOUSE_BUTTON_1
#define VANTUS_MOUSE_BUTTON_RIGHT     VANTUS_MOUSE_BUTTON_2
#define VANTUS_MOUSE_BUTTON_MIDDLE    VANTUS_MOUSE_BUTTON_3